### ISSUE TITLE
Structure_threader should support setup.py for easier installation

### ISSUE THREAD

**Issue by StuntsPT** [StuntsPT/Structure_threader#12]
Also allows being used with pip.

**Comment by ODiogoSilva** [comment]
Restructure the script directories to better support installation via setup.py in the referenced commit. All components required to run structure_threader are now inside the "structure_threader" directory, which will be installed as a python lib with setup.py. The entry point "structure_threader" was also added to the installation. This creates an executable file that will be placed in "/usr/bin". This way, when a user installs via setup.py, they already have the script available anywhere (although without the .py extension).

Fell free to complete some fields in the setup.py, such as the e-mail and classifiers.

Also added ez_setup.py script to allow installation on systems that do not have setuptools installed.

**Comment by StuntsPT** [comment]
Thanks!
I've made some required changes and now it's merged into `master`.
v0.2 is now in viewing distance.
