### ISSUE TITLE
Sort the individuals by population before sorting

### ISSUE THREAD

**Issue by StuntsPT** [StuntsPT/Structure_threader#18]
If a user provides a structure file that is not sorted by population, the result is a messy plot.
The plot function (or even better, the parser) should sort the individuals by their population value before plotting.

**Comment by ODiogoSilva** [comment]
What if the user does not wish to sort individuals by population, explicitly? I'm thinking of cases where the user suspects of another kind of structure that is not driven by the established populations.

**Comment by StuntsPT** [comment]
In that case our plotting that issues population names is just plain wrong, because the plotting is sorted.
(the population divisions simply add the number of individuals of each population and assumes they are already sorted by this order).

**Comment by StuntsPT** [comment]
Also, if what you mention is the purpose of the analysis, than the input file should reflect that order.
Does this sound reasonable to you?

**Comment by StuntsPT** [comment]
Better yet.
Sort the plot based on the order provided in the "popfile". Commit f135955fea3d47b002e0e397a42a398a12aa5c19 adds the popfile input to _Structure_threader_, so now only a few changes to the plotting function are required,
