### ISSUE TITLE
Add a verification to see if 'popfile' exists and is a file to sanity checks.

### ISSUE THREAD

**Issue by StuntsPT** [StuntsPT/Structure_threader#23]
Title says is all.
Currently if an unexisting file is specified as `--pop` argument, plotting will fail with a python error. We don't want that.

**Comment by ODiogoSilva** [comment]
Added new function to sanity.py, since output_checker was for directories. The new function allows for verification of any path with custom error message.

**Comment by StuntsPT** [comment]
Fixed via a lot of commits, but I gues 1904846d62c626a1c76620d9e869ca68ac0a62bf sums it up.
As an added bonus, now structure_threader also checks if the path to the selected external program works. It had been sitting in the TODO list for a while.
