### ISSUE TITLE
Plotly. Font is deprecated

### ISSUE THREAD

**Issue by 3nrique0** [StuntsPT/Structure_threader#79]
Hello,
I ran Structure_threader in a virtual environment, I updated pip and all the modules. Once Structure_threader finishes running all the samples, It will create the plots, which do are created, but it pops out this message:

```
/home/user/virtual_envs/Structure_threader/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:318: DeprecationWarning:

plotly.graph_objs.Font is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Font
  - plotly.graph_objs.layout.hoverlabel.Font
  - etc.
```

I hope it will help you keep this code up to the day.
Cheers !

**Comment by StuntsPT** [comment]
I will look into this as soon as I get the chance (although it won't probably be in the next few days)!
Thank you for you for helping *Structure_threader* stay up-to-date.

**Comment by StuntsPT** [comment]
I have just been investigating this, and it is an upstream problem on [plotly.py](https://github.com/plotly/plotly.py).
However, it seems to be fixed on `plotly.py 3.1.1rc1`.
I'll keep the issue open until `3.1.1` is released, though.

**Comment by StuntsPT** [comment]
This seems to have been fixed upstream.
