### ISSUE TITLE
structure_threader with multiple --extra_opts not working

### ISSUE THREAD

**Issue by oviscanadensis** [StuntsPT/Structure_threader#82]
Hello,

I am unable to get the "--extra_opts" flag to work with more than one option.  Here is the code (I have shortened the file names for simplicity):
```javascript
SEED=$RANDOM

structure_threader run -Klist 2 -i ../input/1_bhs_all_table437_5.bed -o ../output --pop 1_bhs_all_table437_5.txt -t 8 -fs ../fastStructure --log bool --seed ${SEED} --extra_opts "prior=logistic full cv=2"
```

This outputs the following:
```java
INFO: Running: fastStructure -K 2 --input /1_bhs_all_table437_5 --output output --format bed --seed 5790 --prior=logistic --full --cv=2
INFO: Writing logfile for K2, replicate 1. Please wait...
INFO: 
==============================

INFO: All 1 jobs finished successfully.
```
This suggests that the extra_opts worked.  However, when I check the output,
1) The log file says, "%s prior is not currently implemented, defaulting to the simple prior"
2) The files that should be produces by "full" are not saved in the output directory.

If I run the same code with the logistic option only, the logistic option works fine:
```java
SEED=$RANDOM

structure_threader run -Klist 2 -i ../input/1_bhs_all_table437_5.bed -o ../output --pop 1_bhs_all_table437_5.txt -t 8 -fs ../fastStructure --log bool --seed ${SEED} --extra_opts "prior=logistic"
```

I have tried multiple approaches and cannot get the program to accept multiple extra options.  Will you please help?  Thanks!

**Comment by StuntsPT** [comment]
Hi @oviscanadensis, thank you for reporting the issue. Somehow I did not get an email notification regarding the issue, but I'll be taking a look at it ASAP.
Expect an answer in the next few days.

**Comment by StuntsPT** [comment]
The issue seems to manifest when passing more than one extra argument to `--extra_opts`.
Also, I did not thank you for the excellent bug report - **very** complete. You clearly went through hoops to provide it. So, thank you! I wish all bug reports were this complete.

**Comment by oviscanadensis** [comment]
I'm glad that you could easily replicate the issue from my description.  Thanks for working on this and providing updates!

**Comment by StuntsPT** [comment]
Found it!
In a few minutes a new version of *Structure_threader* (1.2.15) will be available on pypi. This version should have this bug fixed.
Also, just FYI, I mentioned your handle in the [changelog](https://github.com/StuntsPT/Structure_threader/blob/master/CHANGELOG.md). =-)
