### ISSUE TITLE
Can this program  generate Delta K diagram? After "job finished successfully", bestk folder only has two text files, evanno.txt and summary.txt....

### ISSUE THREAD

**Issue by Maotingru** [StuntsPT/Structure_threader#90]
Hi, can this program generate Delta K diagram? After "job finished successfully", bestk folder only has two text files, evanno. txt and summary.txt....  What code do I need to enter if can do that? If not, how do I convert them into k graphs?

**Comment by StuntsPT** [comment]
Dear @Maotingru ,
Sorry for the delayed response, I only saw the issue notification today.
*Structure_threader* will not generate a Delta K diagram, but that information is made available.
Inside the file `evanno.txt` that you mention you will find a section that looks something like this:

```
# K     Reps    Mean LnP(K)     Stdev LnP(K)    Ln'(K)  |Ln''(K)|       Delta K
1       10      -839.3600       0.1075  NA      NA      NA
2       10      -796.8700       0.4191  42.490000       34.350000       81.956247
3       10      -788.7300       1.7576  8.140000        11.540000       6.565939
4       10      -769.0500       0.9664  19.680000       16.770000       17.353435
5       10      -766.1400       4.4137  2.910000        9.050000        2.050450
6       10      -772.2800       3.8401  -6.140000       9.280000        2.416616
7       10      -787.7000       6.1143  -15.420000      5.450000        0.891356
8       10      -808.5700       4.6133  -20.870000      NA      NA
```
You can use the data here to easily plot either a Mean LnP(K) plot, or a DeltaK plot, using your favourite plotting software/library.

Best,

Francisco
