### ISSUE TITLE
multiple runs return identical likelihood 

### ISSUE THREAD

**Issue by andycrowl** [StuntsPT/Structure_threader#96]
Hi --

I'm having an issue with all of my runs (within a given K) reporting an identical likelihood value and, therefore, a standard deviation of zero. Looking into my outputs, I have a seed.txt file that lists an identical seed value for all runs. I have attempted to run the program with and without the --seed flag. Any thoughts would be much appreciated! 

Thanks!
Andy

**Comment by StuntsPT** [comment]
Hi Andy,
This was a problem in the past, but we fixed that bug. =-)
Can you please share the version of *Structure_threader* you are using, as well as the value you are passing to `--seed`?
Thanks!

**Comment by elizeng** [comment]
Adding the following flags should resolve that issue

--extra_opts "-D 10000"

**Comment by andycrowl** [comment]
Thanks for the quick response! 
I'm running Version 1.3.10 on my university's HPC. Thanks @elizeng, I gave the -D flag a try.

COMMANDS:

module load structure/2.3.4
module load structure_threader/1.3.10

structure_threader \
    run \
    -Klist 1 2 3 4 5 6 7 8 \
    -R 10 \
    -i alleles.as2x.PUBE_ROGE_BREV.str.thin \
    -o output \
    -t 40 \
    -st ${HPC_STRUCTURE_BIN}/structure \
    --log 1 \
    --seed 35881 \
    --extra_opts "-D 10000"

RESULTS:
seed.txt lists identical values for the first 40 runs (note I requested 40 threads) and then starts using random numbers after that.


Any insights into where I went wrong?

**Comment by StuntsPT** [comment]
Hummm. I think I know what is going on.
The `modules load (...)` lines suggest you are using a SLURM or SLURM-like job submission system.
If that is so, what is likely occurring is that the same seed is being passed to each of the jobs your submission system is running in parallel. The way I see you can solve this is by finding a way to prefix your seed value with the job number or something similar. Depending on the job submission system your university's HPC is using there might be some options on the table for you.

**Comment by andycrowl** [comment]
Ah very good. Yes, I'm submitting jobs through SLURM. That makes sense. I'll see if I can come up with a way to feed it random numbers. Thanks so much for your help!!

**Comment by StuntsPT** [comment]
I took a little dive into this and found out there are some env vars you can use that *should* provide you with a different number for your seeds.
Looking at [this documentation](https://docs.icer.msu.edu/Slurm_Environment_Variables/) I would bet on `$SLURM_TASK_PID` or `$SLURM_JOBID`, but without access to a SLURM server I can only guess.
I'm going to close the issue, but if you do find a solution, please do share it here as it might be useful to other users in the future (and I might add it to the docs - crediting you, of course).
